live_config_reload = true

[window]
padding = { x = 5, y = 5 }

[scrolling]
multiplier = 1

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size = 11.5

[mouse]
hide_when_typing = true
