live_config_reload = true

[scrolling]
multiplier = 2

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size = 12

[window]
padding = { x = 12, y = 15 }
# opacity = 0.9
blur = true
dynamic_padding = true
